### PR TITLE
Travel agency template

### PR DESCRIPTION
**Pull request by frenchzilla**

### CODE REVIEW

**Comment by zeknox** [comment]
Hey @frenchzilla sorry for the delay here but I just pulled down this pull request and there are no files or folders in here. Could you please look into this and see if you can get the proper files added back into this branch.

**Comment by frenchzilla** [comment]
question for you.
I have an idea for a solid template. It would be a malicious attachment
theme without the need for a website (or at least for the user to browse
to).  However, I would like to run this in the context of PF for the
reporting/tracking/emailing features and of course to share with the
community.

The attachment would be a batch file disguised to look like an excel doc.
Can you think of a windows command that PF would register?

On Wed, Oct 22, 2014 at 3:25 PM, Brandon McCann notifications@github.com
wrote:

> Hey @frenchzilla https://github.com/frenchzilla sorry for the delay
> here but I just pulled down this pull request and there are no files or
> folders in here. Could you please look into this and see if you can get the
> proper files added back into this branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pentestgeek/phishing-frenzy-templates/pull/4#issuecomment-60140578
> .

## 

Thank You,
Nate French

**Comment by zeknox** [comment]
You basically need to make an HTTP POST request to the RESTful API running on phishing frenzy that is in charge of logging. You could look at the credential harvesting guide here to get more information on the way PF runs the API.
http://www.phishingfrenzy.com/resources/credential_harvesting

If powershell is an option, this looks like a cmdlet that would work well to make the HTTP POST request
http://technet.microsoft.com/en-us/library/hh849971.aspx

**Comment by frenchzilla** [comment]
Thanks I will look into this.

Did you have a chance to check out my latest PR?  I think its all set for
merging,  Let me know if i need to fix anything.

On Fri, Oct 24, 2014 at 2:22 PM, Brandon McCann notifications@github.com
wrote:

> You basically need to make an HTTP POST request to the RESTful API running
> on phishing frenzy that is in charge of logging. You could look at the
> credential harvesting guide here to get more information on the way PF runs
> the API.
> http://www.phishingfrenzy.com/resources/credential_harvesting
> 
> If powershell is an option, this looks like a cmdlet that would work well
> to make the HTTP POST request
> http://technet.microsoft.com/en-us/library/hh849971.aspx
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pentestgeek/phishing-frenzy-templates/pull/4#issuecomment-60428424
> .

## 

Thank You,
Nate French

**Pull request closed without merging**
